@startuml

title Classes - Class Diagram

class ExerciseView
class CreateExerciseController
class SerieView
class Serie
class Exercise

ExerciseView --> CreateExerciseController
ExerciseView --> SerieView
ExerciseView --> Exercise
CreateExerciseController --> Exercise
Exercise --> Serie
ExerciseView --> Serie
SerieView --> Serie

@enduml