@startuml

state INITIAL
state OPENED_TRAININGS
state OPENED_TRAINING
state OPENED_EXERCISES
state OPENED_EXERCISE
state OPENED_SERIE
state FINAL

[*] --> INITIAL
INITIAL --> OPENED_TRAININGS : Login

OPENED_TRAININGS --> OPENED_TRAINING : OpenTraining
OPENED_TRAININGS --> OPENED_TRAININGS : CreateTraining
OPENED_TRAININGS --> OPENED_EXERCISES : OpenExercises

OPENED_TRAINING --> OPENED_TRAININGS : UpdateTraining
OPENED_TRAINING --> OPENED_TRAININGS : DeleteTraining
OPENED_TRAINING --> OPENED_TRAININGS : OpenTrainings
OPENED_TRAINING --> OPENED_TRAINING : CreateExercise
OPENED_TRAINING --> OPENED_TRAINING : AddExercise
OPENED_TRAINING --> OPENED_EXERCISE : OpenExercise

OPENED_EXERCISES --> OPENED_EXERCISE : OpenExercise
OPENED_EXERCISES --> OPENED_EXERCISES : CreateExercise
OPENED_EXERCISES --> OPENED_TRAININGS : OpenTrainings

OPENED_EXERCISE --> OPENED_EXERCISES : UpdateExercise
OPENED_EXERCISE --> OPENED_EXERCISES : DeleteExercise
OPENED_EXERCISE --> OPENED_EXERCISE : CreateSerie
OPENED_EXERCISE --> OPENED_TRAINING : UpdateExercise
OPENED_EXERCISE --> OPENED_TRAINING : DeleteExercise
OPENED_EXERCISE --> OPENED_SERIE : OpenSerie
OPENED_EXERCISE --> OPENED_TRAININGS : OpenTrainings

OPENED_SERIE --> OPENED_EXERCISE : UpdateSerie
OPENED_SERIE --> OPENED_EXERCISE : DeleteSerie
OPENED_SERIE --> OPENED_TRAININGS : OpenTrainings

OPENED_TRAININGS --> FINAL : Logout
OPENED_EXERCISES --> FINAL : Logout
OPENED_TRAINING --> FINAL : Logout
OPENED_EXERCISE --> FINAL : Logout
OPENED_SERIE --> FINAL : Logout

@enduml